### ISSUE TITLE
Inhabitants needs constructor 

### ISSUE THREAD

**Issue by SuperMechaDeathChrist2000bcVersion4Beta** [Preston159/apcsbomberman#3]

**Comment by lbkulinski** [comment]
Technically it doesn't need to define one. If no constructor is defined, a default constructor is automatically created. I can see both sides of the argument, but since there are setter methods, a constructor is not necessarily required.

**Comment by NoahSebenste** [comment]
I believe the reason SuperMechaDeathChrist2000bcVersion4Beta posted this as an issue was because there were some fields in the Bomberman class that could be initialized by sending them to Inhabitant's constructor using super().  However this is something we'll probably figure out next class.  (Btw bomberman is a subclass of inhabitant incase anyone didn't know).

**Comment by lbkulinski** [comment]
Yeah we'll figure it out next class. And Bomberman, Brick, and Bomb should all extend Inhabitant.

**Comment by ettfemnio** [comment]
I've added two constructors (both an im- and ex-plicit) for Inhabitant.  For future reference, please don't use GitHub issues for comments like this, use Slack instead (which I will get set up for everyone in class tomorrow).

**Comment by SuperMechaDeathChrist2000bcVersion4Beta** [comment]
k
